### ISSUE TITLE
experience bar

### ISSUE THREAD

**Issue by Schaefers** [tales/tales-client#42]
Would be nice, if there would be an experience bar, showing the current exp and the exp needed to reach the next level.

**Comment by Schaefers** [comment]
okay, found the exp bar, but it would be nice if it shows values (the health bar, too)

**Comment by bjorn** [comment]
The bar intentionally does not show values since this is too much clutter in my opinion. You should be able to see the exact values in the Character tab.

I'm not sure what the current status of the leveling system is, but at some point we planned for the level progression to be based on skill levels, which in turn would each have their own XP. As such it would not be possible to show any meaningful numbers apart from the general progress.
